### ISSUE TITLE
Can't either run or build

### ISSUE THREAD

**Issue by meshr-net** [carloalbertobarbano/AndroidNativeInterface#1]
Hi,

Your binaries are 32bit. So I get this error:
CANNOT LINK EXECUTABLE "termux-acceleration": "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 64-bit instead of 32-bit

Could you make instruction how to build your cpp files or to share make files? 

Thanks

**Comment by ghost** [comment]
@meshr-net,
1. You need the custom ndk sysroot and header android_native_app_glue.h since Termux uses shrinked sysroot.
[ndksysroot.tar.gz](https://github.com/carloalbertobarbano/AndroidNativeInterface/files/1935352/ndksysroot.tar.gz) - download this.

2. Command for compilation (termux-acceleration was used as example):
```
clang++ -I. --sysroot=./ndk-sysroot-23 AndroidSensorManager.cpp termux-acceleration.cpp -o termux-acceleration -landroid
```

3. To run these programs:
```
[termux]:~/dev/AndroidNativeInterface:$ env -i LD_PRELOAD=${PREFIX}/lib/libc++_shared.so ./termux-acceleration
{
	'x': '0.723071',
	'y': '0.454912',
	'z': '9.629773'
}
```

**Comment by carloalbertobarbano** [comment]
Thanks @xeffyr

**Comment by meshr-net** [comment]
Thank you! You saved my day. 
I compiled it with this command:
``/opt/android-ndk-r16b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-g++ -I. --sysroot /opt/android-ndk-r16b/platforms/ndk-sysroot-23/ AndroidSensorManager.cpp termux-acceleration.cpp -o termux-acceleration -landroid -I /opt/android-ndk-r16b/platforms/ndk-sysroot-23/data/data/com.termux/files/usr/include/c++/v1/ -I /opt/android-ndk-r16b/platforms/android/  -fPIE –pie``
I had to remove “SensorError::” from ``AndroidSensorManager.cpp`` because of these errors:
``AndroidSensorManager.cpp:25:17: error: 'SensorError' is not a class or namespace
   if(res)*res = SensorError::SENSOR_NOT_FOUND;
                 ^
AndroidSensorManager.cpp:81:16: error: 'SensorError' is not a class or namespace
  if(res)*res = SensorError::SENSOR_FREEZE;``

it works now!

**Comment by carloalbertobarbano** [comment]
Actually, you can build these files directly on your android phone, using gcc installed with termux. That's the way I did it

**Comment by meshr-net** [comment]
Thank you. It has been compiled inside termux without modifying AndroidSensorManager.cpp. It is even better!
